# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-03-25 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170324_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ball',
            options={'verbose_name': 'Ball', 'verbose_name_plural': 'Ball'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Child', 'verbose_name_plural': 'Child'},
        ),
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Clothes', 'verbose_name_plural': 'Clothes'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name': 'Colors', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'UserInfo', 'verbose_name_plural': 'UserInfo'},
        ),
        migrations.AddField(
            model_name='child',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], default=0),
        ),
    ]
